/** Quiet Analog Atelier: health checks diagnose local records first; maintenance actions require an explicit user decision. */
import { db, notifyLibraryChanged, notifyPlaybackChanged } from "@/lib/database";
import type { MusicTrack } from "@/types/music";

export interface LibraryStorageSummary { tracks: number; audioBytes: number; artworkBytes: number; waveformBytes: number; totalBytes: number; quota?: number; usage?: number; available?: number; }
export interface LibraryHealthReport { healthyTracks: number; invalidMetadata: Array<{ id: string; title: string; reason: string }>; missingAudio: Array<{ id: string; title: string }>; duplicateCandidates: Array<{ fingerprint: string; trackIds: string[]; titles: string[] }>; orphanedPlaylistReferences: Array<{ playlistId: string; playlistName: string; trackIds: string[] }>; orphanedQueueReferences: string[]; orphanedPlaybackEvents: string[]; }

const trackName = (track: MusicTrack) => track.title?.trim() || "Untitled track";

export async function getLibraryStorageSummary(): Promise<LibraryStorageSummary> {
  const tracks = await db.tracks.toArray(); const audioBytes = tracks.reduce((total, track) => total + (track.audioBlob?.size ?? 0), 0); const artworkBytes = tracks.reduce((total, track) => total + (track.coverBlob?.size ?? 0), 0); const waveformBytes = tracks.reduce((total, track) => total + (track.waveform?.byteLength ?? 0), 0); const estimate = typeof navigator !== "undefined" ? await navigator.storage?.estimate?.() : undefined;
  return { tracks: tracks.length, audioBytes, artworkBytes, waveformBytes, totalBytes: audioBytes + artworkBytes + waveformBytes, quota: estimate?.quota, usage: estimate?.usage, available: estimate?.quota && estimate?.usage ? Math.max(0, estimate.quota - estimate.usage) : undefined };
}

export async function inspectLibraryHealth(): Promise<LibraryHealthReport> {
  const [tracks, playlists, queue, events] = await Promise.all([db.tracks.toArray(), db.playlists.toArray(), db.queues.get("primary"), db.playbackEvents.toArray()]); const ids = new Set(tracks.map((track) => track.id)); const fingerprintMap = new Map<string, MusicTrack[]>(); const invalidMetadata: LibraryHealthReport["invalidMetadata"] = []; const missingAudio: LibraryHealthReport["missingAudio"] = [];
  for (const track of tracks) { if (!track.audioBlob || !track.audioBlob.size) missingAudio.push({ id: track.id, title: trackName(track) }); if (!track.title?.trim() || !track.artist?.trim() || !track.album?.trim()) invalidMetadata.push({ id: track.id, title: trackName(track), reason: !track.title?.trim() ? "Missing title" : !track.artist?.trim() ? "Missing artist" : "Missing album" }); const records = fingerprintMap.get(track.fingerprint) ?? []; records.push(track); fingerprintMap.set(track.fingerprint, records); }
  const duplicateCandidates = Array.from(fingerprintMap.entries()).filter(([, records]) => records.length > 1).map(([fingerprint, records]) => ({ fingerprint, trackIds: records.map((record) => record.id), titles: records.map(trackName) })); const orphanedPlaylistReferences = playlists.map((playlist) => ({ playlistId: playlist.id, playlistName: playlist.name, trackIds: playlist.trackIds.filter((id) => !ids.has(id)) })).filter((issue) => issue.trackIds.length); const orphanedQueueReferences = (queue?.trackIds ?? []).filter((id) => !ids.has(id)); const orphanedPlaybackEvents = events.filter((event) => event.trackId && !ids.has(event.trackId)).map((event) => event.id); const healthyTracks = tracks.length - new Set([...missingAudio.map((issue) => issue.id), ...invalidMetadata.map((issue) => issue.id)]).size;
  return { healthyTracks, invalidMetadata, missingAudio, duplicateCandidates, orphanedPlaylistReferences, orphanedQueueReferences, orphanedPlaybackEvents };
}

export async function clearWaveformCache() { await db.transaction("rw", db.tracks, async () => { const tracks = await db.tracks.toArray(); await Promise.all(tracks.filter((track) => track.waveform?.length).map((track) => db.tracks.update(track.id, { waveform: undefined, waveformVersion: undefined }))); }); notifyLibraryChanged(); }
export async function removeOrphanedReferences() { await db.transaction("rw", db.tracks, db.playlists, db.queues, db.playbackEvents, async () => { const ids = new Set((await db.tracks.toArray()).map((track) => track.id)); const playlists = await db.playlists.toArray(); await Promise.all(playlists.map((playlist) => db.playlists.update(playlist.id, { trackIds: playlist.trackIds.filter((id) => ids.has(id)), updatedAt: Date.now() }))); const queue = await db.queues.get("primary"); if (queue) await db.queues.put({ ...queue, trackIds: queue.trackIds.filter((id) => ids.has(id)), updatedAt: Date.now() }); const events = await db.playbackEvents.toArray(); await db.playbackEvents.bulkDelete(events.filter((event) => event.trackId && !ids.has(event.trackId)).map((event) => event.id)); }); notifyLibraryChanged(); notifyPlaybackChanged(); }
export async function clearListeningHistory() { await db.transaction("rw", db.tracks, db.playbackEvents, async () => { const tracks = await db.tracks.toArray(); await Promise.all(tracks.map((track) => db.tracks.update(track.id, { lastPlayedAt: undefined, playCount: 0 }))); await db.playbackEvents.clear(); }); notifyLibraryChanged(); notifyPlaybackChanged(); }
export async function clearListeningStatistics() { await db.playbackEvents.clear(); notifyPlaybackChanged(); }
