/** Quiet Analog Atelier: library rows keep collections virtualized while revealing contextual playback actions on demand. */
import { useMemo, useRef } from "react";
import { useVirtualizer } from "@tanstack/react-virtual";
import { Clock3, Disc3, Heart, MoreHorizontal, Music2, Play, UserRound } from "lucide-react";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { toggleFavorite } from "@/lib/database";
import { usePlayerStore } from "@/store/player-store";
import type { MusicTrack, Playlist } from "@/types/music";
import { CoverArt } from "./CoverArt";
import "./empty-state.css";

export type LibrarySection = "songs" | "albums" | "artists" | "favorites" | "recent" | "playlists";
export function formatDuration(value: number) { if (!Number.isFinite(value) || value <= 0) return "—:—"; return `${Math.floor(value / 60)}:${Math.floor(value % 60).toString().padStart(2, "0")}`; }
export function SignalBars({ active }: { active: boolean }) { return <span aria-hidden="true" className={`signal-bars ${active ? "is-active" : ""}`}><i /><i /><i /></span>; }

export function TrackList({ tracks, currentTrackId, playing, onPlay, title, subtitle }: { tracks: MusicTrack[]; currentTrackId?: string; playing: boolean; onPlay: (track: MusicTrack) => void; title: string; subtitle: string }) {
  const parentRef = useRef<HTMLDivElement>(null); const addToQueue = usePlayerStore((state) => state.addToQueue); const rowVirtualizer = useVirtualizer({ count: tracks.length, getScrollElement: () => parentRef.current, estimateSize: () => 62, overscan: 8 }); const items = rowVirtualizer.getVirtualItems();
  return <section className="library-panel" aria-label={title}><div className="library-heading"><div><p className="eyebrow">Collection</p><h1 className="font-display text-[clamp(2rem,4vw,3.65rem)] font-medium tracking-[-.05em] text-[#F6F3EB]">{title}</h1><p className="mt-2 text-sm text-[#9DA7A1]">{subtitle}</p></div><div className="collection-count">{tracks.length.toLocaleString()} tracks</div></div><div className="track-columns"><span>#</span><span>Title</span><span className="hidden sm:block">Album</span><span className="text-right">Time</span></div><div ref={parentRef} className="track-scroll" style={{ maxHeight: "calc(100vh - 270px)" }}><div style={{ height: `${rowVirtualizer.getTotalSize()}px`, position: "relative" }}>{items.map((virtualRow) => { const track = tracks[virtualRow.index]; const active = track.id === currentTrackId; return <div className={`track-row ${active ? "is-current" : ""}`} key={track.id} style={{ transform: `translateY(${virtualRow.start}px)` }}><button className="track-index" onClick={() => onPlay(track)} aria-label={`Play ${track.title}`}>{active ? <SignalBars active={playing} /> : <span>{virtualRow.index + 1}</span>}<Play className="track-play" size={15} fill="currentColor" /></button><button className="flex min-w-0 items-center gap-3 text-left" onClick={() => onPlay(track)}><CoverArt track={track} className="size-9 rounded-lg" /><span className="min-w-0"><span className="block truncate text-sm font-medium text-[#E9E8E1]">{track.title}</span><span className="block truncate text-xs text-[#8F9993]">{track.artist}</span></span></button><span className="hidden truncate text-sm text-[#98A29D] sm:block">{track.album}</span><span className="flex items-center justify-end gap-3"><button className={`favorite-button ${track.isFavorite ? "is-favorite" : ""}`} onClick={() => void toggleFavorite(track.id)} aria-label={track.isFavorite ? "Remove from favorites" : "Add to favorites"}><Heart size={15} fill={track.isFavorite ? "currentColor" : "none"} /></button><span className="w-9 text-right font-mono text-xs text-[#9DA7A1]">{formatDuration(track.duration)}</span><DropdownMenu><DropdownMenuTrigger asChild><button className="hidden text-[#8CA097] hover:text-[#C3D9CC] md:block" aria-label={`Actions for ${track.title}`}><MoreHorizontal size={18} /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => onPlay(track)}>Play now</DropdownMenuItem><DropdownMenuItem onSelect={() => void addToQueue(track.id, "next")}>Play next</DropdownMenuItem><DropdownMenuItem onSelect={() => void addToQueue(track.id)}>Add to queue</DropdownMenuItem></DropdownMenuContent></DropdownMenu></span></div>; })}</div>{!tracks.length && <EmptyTracks />}</div></section>;
}

export function AlbumIndex({ tracks, onPlay }: { tracks: MusicTrack[]; onPlay: (track: MusicTrack) => void }) { const albums = useMemo(() => Object.values(tracks.reduce<Record<string, MusicTrack[]>>((groups, track) => { (groups[`${track.album}::${track.artist}`] ??= []).push(track); return groups; }, {})), [tracks]); return <section className="library-panel"><div className="library-heading"><div><p className="eyebrow">Organized by record</p><h1 className="font-display text-[clamp(2rem,4vw,3.65rem)] font-medium tracking-[-.05em] text-[#F6F3EB]">Albums</h1><p className="mt-2 text-sm text-[#9DA7A1]">A quiet shelf for every record in your library.</p></div><Disc3 className="text-[#8CB9A5]" size={28} /></div>{albums.length ? <div className="album-shelf">{albums.map((album) => <button key={album[0].id} className="album-sleeve text-left" onClick={() => onPlay(album[0])}><div className="relative aspect-square overflow-hidden rounded-xl"><CoverArt track={album[0]} className="size-full" /><span className="absolute inset-0 grid place-items-center bg-[#111514]/0 opacity-0 transition hover:bg-[#111514]/45 hover:opacity-100"><Play size={22} fill="currentColor" /></span></div><span className="mt-3 block truncate text-sm font-medium text-[#F2F1EB]">{album[0].album}</span><span className="mt-1 block truncate text-xs text-[#8F9993]">{album[0].artist} · {album.length} tracks</span></button>)}</div> : <EmptyTracks compact />}</section>; }

export function ArtistIndex({ tracks, onPlay }: { tracks: MusicTrack[]; onPlay: (track: MusicTrack) => void }) { const artists = useMemo(() => Object.values(tracks.reduce<Record<string, MusicTrack[]>>((groups, track) => { (groups[track.artist] ??= []).push(track); return groups; }, {})).sort((a, b) => b.length - a.length), [tracks]); return <section className="library-panel"><div className="library-heading"><div><p className="eyebrow">People & projects</p><h1 className="font-display text-[clamp(2rem,4vw,3.65rem)] font-medium tracking-[-.05em] text-[#F6F3EB]">Artists</h1><p className="mt-2 text-sm text-[#9DA7A1]">The names that shape your collection.</p></div><UserRound className="text-[#8CB9A5]" size={28} /></div>{artists.length ? <div className="artist-index">{artists.map((artist) => <button key={artist[0].artist} className="artist-card" onClick={() => onPlay(artist[0])}><span className="artist-monogram">{artist[0].artist.slice(0, 1).toUpperCase()}</span><span className="min-w-0 text-left"><span className="block truncate font-display text-xl text-[#F2F1EB]">{artist[0].artist}</span><span className="mt-1 block text-xs text-[#8F9993]">{artist.length} {artist.length === 1 ? "track" : "tracks"} in your library</span></span><Play className="ml-auto text-[#8CB9A5]" size={18} fill="currentColor" /></button>)}</div> : <EmptyTracks compact />}</section>; }

export function PlaylistIndex({ playlists, tracks, onPlay, onCreate }: { playlists: Playlist[]; tracks: MusicTrack[]; onPlay: (track: MusicTrack) => void; onCreate: () => void }) { return <section className="library-panel"><div className="library-heading"><div><p className="eyebrow">Your sequences</p><h1 className="font-display text-[clamp(2rem,4vw,3.65rem)] font-medium tracking-[-.05em] text-[#F6F3EB]">Playlists</h1><p className="mt-2 text-sm text-[#9DA7A1]">Made on this device, waiting exactly where you left them.</p></div><button className="quiet-action" onClick={onCreate}>New playlist</button></div>{playlists.length ? <div className="playlist-stack">{playlists.map((playlist) => { const first = tracks.find((track) => track.id === playlist.trackIds[0]); return <button key={playlist.id} className="playlist-card" onClick={() => first && onPlay(first)}><span className="playlist-art"><Music2 size={24} /></span><span className="text-left"><span className="block font-display text-2xl text-[#F2F1EB]">{playlist.name}</span><span className="mt-1 block text-xs text-[#8F9993]">{playlist.trackIds.length} {playlist.trackIds.length === 1 ? "track" : "tracks"}</span></span><Play className="ml-auto text-[#8CB9A5]" size={18} fill="currentColor" /></button>; })}</div> : <div className="empty-compact"><Music2 size={22} /><div><p className="font-medium text-[#EDECE6]">No playlists yet</p><p className="mt-1 text-sm text-[#8F9993]">Build a sequence for a day, a drive, or a particular kind of focus.</p></div><button className="quiet-action" onClick={onCreate}>Create one</button></div>}</section>; }

export function EmptyTracks({ compact = false }: { compact?: boolean }) { const openImport = () => document.querySelector<HTMLButtonElement>(".import-button")?.click(); return <div className={compact ? "empty-compact" : "empty-library"}><div className="empty-art sleeve-field"><span className="sleeve-index">01 / LOCAL</span><img src="placeholder.png" alt="Record sleeve resting on a listening desk" /><span className="sleeve-signal"><i /><i /><i /></span></div><div className="empty-copy"><p className="eyebrow">A collection begins here</p><p className="mt-2 font-display text-3xl tracking-[-.04em] text-[#F0EFE8]">The shelves are clear.</p><p className="mt-3 max-w-md text-sm leading-6 text-[#9BA49F]">Bring in the records you already love. They will stay catalogued, playable, and close at hand—even offline.</p><button className="empty-import-action" onClick={openImport}>Import local music <span>↗</span></button></div></div>; }
export function RecentEmpty() { return <div className="empty-compact"><Clock3 className="text-[#8CB9A5]" size={22} /><div><p className="font-medium text-[#EDECE6]">Nothing in the recent stack</p><p className="mt-1 text-sm text-[#8F9993]">Tracks you play will gather here quietly.</p></div></div>; }
