/** Quiet Analog Atelier: the playlist workspace keeps detail editing within the same persistent listening desk. */
import { Music2, Play, Plus } from "lucide-react";
import type { MusicTrack, Playlist } from "@/types/music";
import { PlaylistDetail } from "./PlaylistDetail";

export function PlaylistWorkspace({ playlists, tracks, selectedId, onSelect, onCreate, onPlay }: { playlists: Playlist[]; tracks: MusicTrack[]; selectedId?: string; onSelect: (id?: string) => void; onCreate: () => void; onPlay: (track: MusicTrack, queue: MusicTrack[]) => void }) {
  const selected = playlists.find((playlist) => playlist.id === selectedId);
  if (selected) return <PlaylistDetail playlist={selected} tracks={tracks} onBack={() => onSelect(undefined)} onPlay={onPlay} />;
  return <section className="library-panel"><div className="library-heading"><div><p className="eyebrow">Your sequences</p><h1 className="font-display text-[clamp(2rem,4vw,3.65rem)] font-medium tracking-[-.05em] text-[#F6F3EB]">Playlists</h1><p className="mt-2 text-sm text-[#9DA7A1]">Made on this device, waiting exactly where you left them.</p></div><button className="quiet-action" onClick={onCreate}><Plus size={14} className="mr-1 inline" />New playlist</button></div>{playlists.length ? <div className="playlist-stack">{playlists.map((playlist) => { const items = playlist.trackIds.map((id) => tracks.find((track) => track.id === id)).filter(Boolean) as MusicTrack[]; return <article key={playlist.id} className="playlist-card"><button className="flex min-w-0 flex-1 items-center gap-4 text-left" onClick={() => onSelect(playlist.id)}><span className="playlist-art"><Music2 size={24} /></span><span className="min-w-0"><span className="block truncate font-display text-2xl text-[#F2F1EB]">{playlist.name}</span><span className="mt-1 block text-xs text-[#8F9993]">{items.length} {items.length === 1 ? "track" : "tracks"} · local sequence</span></span></button><button className="icon-button text-[#8CB9A5]" onClick={() => items[0] && onPlay(items[0], items)} aria-label={`Play ${playlist.name}`}><Play size={18} fill="currentColor" /></button></article>; })}</div> : <div className="empty-compact"><Music2 size={22} /><div><p className="font-medium text-[#EDECE6]">No playlists yet</p><p className="mt-1 text-sm text-[#8F9993]">Build a sequence for a day, a drive, or a particular kind of focus.</p></div><button className="quiet-action" onClick={onCreate}>Create one</button></div>}</section>;
}
