/** Quiet Analog Atelier: playlist detail is a local editing surface with immediate ordering persistence. */
import { useEffect, useMemo, useState } from "react";
import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { ArrowLeft, ListPlus, MoreHorizontal, Play, Shuffle, Trash2 } from "lucide-react";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { reorderIds, savePlaylist } from "@/lib/collection-actions";
import { recordPlaybackEvent } from "@/lib/database";
import { usePlayerStore } from "@/store/player-store";
import type { MusicTrack, Playlist } from "@/types/music";
import { CoverArt } from "./CoverArt";
import { formatDuration } from "./LibraryViews";

export function PlaylistDetail({ playlist, tracks, onBack, onPlay: playTrack }: { playlist: Playlist; tracks: MusicTrack[]; onBack: () => void; onPlay: (track: MusicTrack, queue: MusicTrack[]) => void }) {
  const [editingName, setEditingName] = useState(false); const [name, setName] = useState(playlist.name); const [adding, setAdding] = useState(false);
  useEffect(() => setName(playlist.name), [playlist.id, playlist.name]);
  const playlistTracks = useMemo(() => playlist.trackIds.map((id) => tracks.find((track) => track.id === id)).filter(Boolean) as MusicTrack[], [playlist.trackIds, tracks]);
  const total = playlistTracks.reduce((sum, track) => sum + track.duration, 0);
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  const update = async (changes: Partial<Playlist>) => savePlaylist({ ...playlist, ...changes, updatedAt: Date.now() });
  const dragEnd = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; const from = playlist.trackIds.indexOf(String(active.id)); const to = playlist.trackIds.indexOf(String(over.id)); void update({ trackIds: reorderIds(playlist.trackIds, from, to) }); };
  const addTrack = (trackId: string) => { if (playlist.trackIds.includes(trackId)) return; void update({ trackIds: [...playlist.trackIds, trackId] }); };
  const removeTrack = (trackId: string) => void update({ trackIds: playlist.trackIds.filter((id) => id !== trackId) });
  const onPlay = (track: MusicTrack, queue: MusicTrack[]) => { void recordPlaybackEvent("playlist-play", { trackId: track.id, playlistId: playlist.id }); playTrack(track, queue); };
  const playRandom = () => { const pick = playlistTracks[Math.floor(Math.random() * playlistTracks.length)]; if (pick) onPlay(pick, playlistTracks); };
  return <section className="library-panel playlist-detail"><button className="back-link" onClick={onBack}><ArrowLeft size={16} />All playlists</button><div className="playlist-detail-header"><div className="playlist-detail-mark"><span>LOCAL</span></div><div className="min-w-0 flex-1"><p className="eyebrow">Handmade sequence</p>{editingName ? <input className="playlist-name-input" value={name} autoFocus onChange={(event) => setName(event.target.value)} onBlur={() => { setEditingName(false); const next = name.trim(); if (next && next !== playlist.name) void update({ name: next }); else setName(playlist.name); }} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }} /> : <button className="text-left" onClick={() => setEditingName(true)} aria-label="Rename playlist"><h1 className="font-display text-[clamp(2rem,5vw,4.1rem)] tracking-[-.06em] text-[#F5F3EC]">{playlist.name}</h1></button>}<p className="mt-2 text-sm text-[#9BA49F]">{playlistTracks.length} {playlistTracks.length === 1 ? "track" : "tracks"} · {formatDuration(total)}</p><div className="mt-5 flex flex-wrap gap-2"><button className="playlist-play-button" onClick={() => playlistTracks[0] && onPlay(playlistTracks[0], playlistTracks)}><Play size={16} fill="currentColor" />Play</button><button className="quiet-action" onClick={playRandom}><Shuffle size={14} className="mr-1 inline" />Shuffle</button><button className="quiet-action" onClick={() => setAdding(true)}><ListPlus size={14} className="mr-1 inline" />Add songs</button></div></div></div>{playlistTracks.length ? <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={dragEnd}><SortableContext items={playlist.trackIds} strategy={verticalListSortingStrategy}><div className="playlist-track-list">{playlistTracks.map((track, index) => <PlaylistRow key={track.id} track={track} index={index} onPlay={() => onPlay(track, playlistTracks)} onRemove={() => removeTrack(track.id)} />)}</div></SortableContext></DndContext> : <div className="playlist-empty"><ListPlus className="text-[#8CB9A5]" size={22} /><p className="font-display text-2xl text-[#F1F0E9]">Leave room for a first track.</p><p className="mt-2 max-w-sm text-sm leading-6 text-[#949E98]">Add recordings from your locally imported library. This list and its order are kept in IndexedDB.</p><button className="quiet-action mt-5" onClick={() => setAdding(true)}>Add songs</button></div>}{adding && <AddTracks tracks={tracks.filter((track) => !playlist.trackIds.includes(track.id))} onAdd={addTrack} onClose={() => setAdding(false)} />}</section>;
}

function PlaylistRow({ track, index, onPlay, onRemove }: { track: MusicTrack; index: number; onPlay: () => void; onRemove: () => void }) {
  const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id: track.id }); const addToQueue = usePlayerStore((state) => state.addToQueue);
  return <div ref={setNodeRef} className="playlist-track-row" style={{ transform: CSS.Transform.toString(transform), transition }}><button className="playlist-track-index" {...attributes} {...listeners} aria-label={`Reorder ${track.title}`}>{String(index + 1).padStart(2, "0")}</button><button className="flex min-w-0 flex-1 items-center gap-3 text-left" onClick={onPlay}><CoverArt track={track} className="size-10 rounded-lg" /><span className="min-w-0"><span className="block truncate text-sm font-medium text-[#EEEDE6]">{track.title}</span><span className="block truncate text-xs text-[#8D9791]">{track.artist} · {track.album}</span></span></button><span className="hidden w-12 text-right font-mono text-xs text-[#89938D] sm:block">{formatDuration(track.duration)}</span><DropdownMenu><DropdownMenuTrigger asChild><button className="icon-button" aria-label={`More actions for ${track.title}`}><MoreHorizontal size={17} /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => void addToQueue(track.id, "next")}>Play next</DropdownMenuItem><DropdownMenuItem onSelect={() => void addToQueue(track.id)}>Add to queue</DropdownMenuItem><DropdownMenuItem className="text-red-400" onSelect={onRemove}><Trash2 size={14} className="mr-2" />Remove from playlist</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>;
}

function AddTracks({ tracks, onAdd, onClose }: { tracks: MusicTrack[]; onAdd: (id: string) => void; onClose: () => void }) { return <div className="playlist-add-overlay" onMouseDown={onClose}><div className="playlist-add-panel" onMouseDown={(event) => event.stopPropagation()} role="dialog" aria-modal="true" aria-label="Add songs to playlist"><div className="flex items-center justify-between"><div><p className="eyebrow">Local library</p><h2 className="font-display text-2xl text-[#F2F1EA]">Add songs</h2></div><button className="icon-button" onClick={onClose}>×</button></div><div className="mt-5 max-h-[55vh] overflow-auto">{tracks.length ? tracks.map((track) => <button className="playlist-add-row" key={track.id} onClick={() => onAdd(track.id)}><CoverArt track={track} className="size-9 rounded-lg" /><span className="min-w-0 text-left"><span className="block truncate text-sm text-[#ECEBE5]">{track.title}</span><span className="block truncate text-xs text-[#8C9690]">{track.artist}</span></span><ListPlus className="ml-auto text-[#8CB9A5]" size={17} /></button>) : <p className="py-10 text-center text-sm text-[#939D97]">Every imported track is already here.</p>}</div><button className="quiet-action mt-5" onClick={onClose}>Done</button></div></div>; }
