/** Quiet Analog Atelier: this lightweight live spectrum uses the single Web Audio analyser and never allocates decoded audio buffers. */
import { useEffect, useRef } from "react";
import type { MutableRefObject } from "react";
import type { AudioEngine } from "@/lib/audio-engine";

export function Waveform({ engineRef, playing, progress, amplitudes, onSeek }: { engineRef: MutableRefObject<AudioEngine | null>; playing: boolean; progress: number; amplitudes?: Uint8Array; onSeek: (time: number) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const frameRef = useRef<number | undefined>(undefined); const seekingRef = useRef(false);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const context = canvas.getContext("2d"); if (!context) return; const resize = () => { const bounds = canvas.getBoundingClientRect(); const pixelRatio = window.devicePixelRatio || 1; canvas.width = Math.max(1, Math.floor(bounds.width * pixelRatio)); canvas.height = Math.max(1, Math.floor(bounds.height * pixelRatio)); context.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0); }; const observer = new ResizeObserver(resize); observer.observe(canvas); resize(); const render = () => { const bounds = canvas.getBoundingClientRect(); const width = bounds.width; const height = bounds.height; context.clearRect(0, 0, width, height); const liveData = engineRef.current?.getFrequencyData() ?? new Uint8Array(24); const data = amplitudes?.length ? amplitudes : liveData; const bars = Math.min(64, Math.max(24, data.length)); const gap = 2; const barWidth = Math.max(1, (width - gap * (bars - 1)) / bars); for (let index = 0; index < bars; index += 1) { const source = data[Math.floor((index / bars) * data.length)] ?? 0; const amplitude = amplitudes?.length ? Math.max(0.08, source / 255) : playing ? Math.max(0.12, source / 255) : 0.14 + ((index % 5) * 0.015); const barHeight = Math.max(3, amplitude * height); context.fillStyle = index / bars <= progress ? "#8CB9A5" : "rgba(232,237,232,.22)"; context.fillRect(index * (barWidth + gap), (height - barHeight) / 2, barWidth, barHeight); } if (!amplitudes?.length) frameRef.current = requestAnimationFrame(render); }; render(); return () => { observer.disconnect(); if (frameRef.current) cancelAnimationFrame(frameRef.current); }; }, [amplitudes, engineRef, playing, progress]);
  const seek = (event: React.PointerEvent<HTMLCanvasElement>) => { const bounds = event.currentTarget.getBoundingClientRect(); const ratio = Math.min(1, Math.max(0, (event.clientX - bounds.left) / bounds.width)); const duration = engineRef.current?.duration ?? 0; if (duration) onSeek(ratio * duration); };
  return <canvas ref={canvasRef} className="waveform-canvas" aria-label="Audio progress. Drag or tap to seek." aria-valuemin={0} aria-valuemax={engineRef.current?.duration ?? 0} aria-valuenow={(engineRef.current?.duration ?? 0) * progress} onPointerDown={(event) => { seekingRef.current = true; event.currentTarget.setPointerCapture(event.pointerId); seek(event); }} onPointerMove={(event) => { if (seekingRef.current) seek(event); }} onPointerUp={(event) => { seekingRef.current = false; event.currentTarget.releasePointerCapture(event.pointerId); seek(event); }} onPointerCancel={() => { seekingRef.current = false; }} role="slider" tabIndex={0} onKeyDown={(event) => { if (event.key === "ArrowLeft") onSeek(Math.max(0, (engineRef.current?.currentTime ?? 0) - 5)); if (event.key === "ArrowRight") onSeek((engineRef.current?.currentTime ?? 0) + 5); }} />;
}
